cms/urls.py
from django.urls import path, include

from .views import PostView, PostListView

urlpatterns = [
	path("", PostListView.as_view(), name="cms-post-list"),
	path("<str:post_slug>/", PostView.as_view(), name="cms-post"),
]

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
	path("", views.index, name="home-index"),
]

tavern/urls.py
from django.contrib import admin
from django.urls import path, include

# For serving user uploaded media in development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path("taverns/", include("posts.urls")),
	path("news/", include("cms.urls")),
	path("", include("home.urls")),
]

# For serving user uploaded media in development
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse

class Tavern(models.Model):
	name = models.CharField(max_length=150)
	description = models.TextField(max_length=1024)
	# TODO: Add image field where image is hosted on separate domain. See https://docs.djangoproject.com/en/3.1/topics/security/#user-uploaded-content-security
	image = models.ImageField(upload_to="images/")
	latitude = models.FloatField()
	longitude = models.FloatField()

	def get_absolute_url(self):
		return reverse("posts-tavern", kwargs={"tavern_id": self.id})

	def __str__(self):
		return self.name

class Post(models.Model):
	tavern = models.ForeignKey("Tavern", on_delete=models.CASCADE)
	title = models.CharField(max_length=128)
	author = models.CharField(max_length=8, default="", blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	archived = models.BooleanField(default=False)
	content = models.TextField(max_length=4096)

	def get_absolute_url(self):
		return reverse("posts-post", kwargs={"tavern_id": self.tavern.id, "post_id": self.id})	

	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey("Post", on_delete=models.CASCADE)
	author = models.CharField(max_length=8)
	created_at = models.DateTimeField(auto_now_add=True)
	content = models.CharField(max_length=512)
	
	def get_absolute_url(self):
		return reverse("posts-post", kwargs={"tavern_id": self.post.tavern.id, "post_id": self.post.id})	

	def __str__(self):
		return self.content

home/views.py
from django.shortcuts import render

from posts.models import Tavern

def index(request):
	data = {}
	data["tavern"] = Tavern.objects.get(pk=1)
	return render(request, "home/index.html", data)

home/templates/home/index.html
{% extends "posts/base.html" %}

{% block head %}
	<title>Home | Ceilid</title>
{% endblock %}

{% block body %}
	<div class="grid gap container">
		<div class="grid-item-12">
			{% include "posts/includes/image_header.html" with title="Ceilid" subtitle="The Local Internet Forum" %}
		</div>
		<div class="grid-item-12">
			<h2>About Ceilid</h2>
		</div>
		<div class="grid-item-12">
			<ul>
				<li><h6>Talk with others in your local area. Users share news, tips, opinions, and more.</h6></li>
				<br>
				<li><h6>Thinking of moving to a new place? Check out its page to get info directly from its residents.</h6></li>
				<br>
				<li><h6>Want to talk about national news? Check out your country's page!</h6></li>
				<br>
				<li><h6>Wish there was a page someplace? Start a post on the Ceilid HQ page.</h6></li>
			</ul>
		</div>
		<div class="grid-item-12" style="text-align: center;">
			<a href="{% url 'posts-tavern_list' %}">
				<button>Get Started</button>
			</a>
		</div>
		<div class="grid-item-12">
		</div>
	</div>
{% endblock %}